# Site settings
title: "Ludwig Jacobsson"
email: ludjac@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About me, my projects and my interests.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ludwigjacobsson.se" # the base hostname & protocol for your site
twitter_username: ludjac
github_username:  ludjac
flickr_username: ludjac
kaggle_username: ludjac

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Algorithm developer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
